// <auto-generated />
using System;
using MAD.DataWarehouse.SignOnSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAD.DataWarehouse.SignOnSite.Migrations
{
    [DbContext(typeof(SignOnSiteDbContext))]
    [Migration("20210907010258_AddTable_SiteBriefing")]
    partial class AddTable_SiteBriefing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MAD.DataWarehouse.SignOnSite.Api.Site", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("InternalReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("MAD.DataWarehouse.SignOnSite.Api.SiteAttendance", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInductedToSite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisitor")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("SignoffAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SignonAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("SiteAttendance");
                });

            modelBuilder.Entity("MAD.DataWarehouse.SignOnSite.Api.SiteBriefing", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AcknowledgementCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("SeenCount")
                        .HasColumnType("int");

                    b.Property<bool>("ShouldShowSetByUser")
                        .HasColumnType("bit");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("SiteBriefing");
                });

            modelBuilder.Entity("MAD.DataWarehouse.SignOnSite.Api.SiteAttendance", b =>
                {
                    b.HasOne("MAD.DataWarehouse.SignOnSite.Api.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MAD.DataWarehouse.SignOnSite.Api.SiteAttendance+SACompany", "Company", b1 =>
                        {
                            b1.Property<int>("SiteAttendanceId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SiteAttendanceId");

                            b1.ToTable("SiteAttendance");

                            b1.WithOwner()
                                .HasForeignKey("SiteAttendanceId");
                        });

                    b.OwnsOne("MAD.DataWarehouse.SignOnSite.Api.SiteAttendance+SAUser", "User", b1 =>
                        {
                            b1.Property<int>("SiteAttendanceId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("LastName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SiteAttendanceId");

                            b1.ToTable("SiteAttendance");

                            b1.WithOwner()
                                .HasForeignKey("SiteAttendanceId");
                        });

                    b.Navigation("Company");

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MAD.DataWarehouse.SignOnSite.Api.SiteBriefing", b =>
                {
                    b.HasOne("MAD.DataWarehouse.SignOnSite.Api.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });
#pragma warning restore 612, 618
        }
    }
}
